In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
## Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [16]:
## define the vocabulary size.
voc_size = 10000

In [17]:
ont_hot_representation = [one_hot(words,voc_size) for words in sent]
ont_hot_representation

[[4881, 7772, 6213, 9546],
 [4881, 7772, 6213, 525],
 [4881, 259, 6213, 1717],
 [2665, 9647, 2258, 3967, 6731],
 [2665, 9647, 2258, 3967, 5037],
 [7819, 4881, 5289, 6213, 3426],
 [4330, 6265, 1075, 3967]]

In [18]:
## word embedding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences


In [19]:
import numpy as np
sent_length = 8
## pad sequence makes the length of all the snetences equal
embedded_docs = pad_sequences(ont_hot_representation,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4881 7772 6213 9546]
 [   0    0    0    0 4881 7772 6213  525]
 [   0    0    0    0 4881  259 6213 1717]
 [   0    0    0 2665 9647 2258 3967 6731]
 [   0    0    0 2665 9647 2258 3967 5037]
 [   0    0    0 7819 4881 5289 6213 3426]
 [   0    0    0    0 4330 6265 1075 3967]]


In [22]:
## feature representation
dim = 10 ## only dim number of features
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_shape=(sent_length,)))
model.compile('adam','mse')

/Users/vaibhavkale/Desktop/DL_Projects/ANN_Classification/venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [23]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step


array([[[ 0.00163962, -0.02729607, -0.04441849, -0.04531616,
         -0.01100104,  0.02361951, -0.0298812 , -0.03039666,
         -0.04578999,  0.02733762],
        [ 0.00163962, -0.02729607, -0.04441849, -0.04531616,
         -0.01100104,  0.02361951, -0.0298812 , -0.03039666,
         -0.04578999,  0.02733762],
        [ 0.00163962, -0.02729607, -0.04441849, -0.04531616,
         -0.01100104,  0.02361951, -0.0298812 , -0.03039666,
         -0.04578999,  0.02733762],
        [ 0.00163962, -0.02729607, -0.04441849, -0.04531616,
         -0.01100104,  0.02361951, -0.0298812 , -0.03039666,
         -0.04578999,  0.02733762],
        [-0.01351916, -0.04351104, -0.01891109,  0.02007457,
         -0.04881946, -0.02286243,  0.00697434, -0.01350588,
         -0.03308561, -0.03330064],
        [-0.00050799, -0.03850601, -0.0496449 ,  0.0379531 ,
          0.01525931, -0.01222801, -0.0420285 ,  0.04729268,
          0.00160824,  0.01401103],
        [ 0.00470736, -0.01872668,  0.00855223,  0.0